spring:
  application:
    name: telegram-bot-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: fintracker
      auto-offset-reset: earliest
  cloud:
    config:
      uri: http://localhost:8888
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  telegram:
    bot:
      username: fin_friend_bot
      token: 6965620065:AAHWGtjeF30PC5_hS8x_QeexllYkPagO2xg
